export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#cae6ff",
        "on-primary-container": "#00391a",
        "surface-container": "#edeeef",
        "on-surface": "#191c1d",
        "secondary": "#006492",
        "surface-container-highest": "#e1e3e4",
        "surface-bright": "#f8f9fa",
        "primary-container": "#27ae60",
        "background": "#f8f9fa",
        "on-tertiary-container": "#003919",
        "on-background": "#191c1d",
        "outline": "#6d7a6e",
        "on-tertiary-fixed-variant": "#005228",
        "primary-fixed": "#7efba4",
        "on-secondary-fixed": "#001e2f",
        "surface-variant": "#e1e3e4",
        "surface-container-high": "#e7e8e9",
        "on-primary-fixed": "#00210c",
        "secondary-container": "#58bcfd",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-fixed-dim": "#4ae183",
        "on-surface-variant": "#3d4a3f",
        "on-error-container": "#93000a",
        "on-secondary-container": "#004a6d",
        "primary": "#006d37",
        "on-secondary-fixed-variant": "#004b6f",
        "surface-dim": "#d9dadb",
        "outline-variant": "#bccabc",
        "surface-container-low": "#f3f4f5",
        "on-secondary": "#ffffff",
        "surface-tint": "#006d37",
        "on-primary-fixed-variant": "#005228",
        "error": "#ba1a1a",
        "tertiary-fixed": "#6bfe9c",
        "tertiary": "#006d37",
        "secondary-fixed-dim": "#8ccdff",
        "inverse-primary": "#61de8a",
        "primary-fixed-dim": "#61de8a",
        "on-primary": "#ffffff",
        "inverse-surface": "#2e3132",
        "tertiary-container": "#00af5b",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "surface": "#f8f9fa",
        "on-tertiary-fixed": "#00210c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "48px",
        "base-unit": "8px",
        "margin-mobile": "16px",
        "container-max-width": "1280px",
        "gutter": "24px"
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Montserrat"],
        "display-hero": ["Montserrat"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Montserrat"],
        "headline-lg-mobile": ["Montserrat"]
      },
      fontSize: {
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-hero": ["60px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
